### ISSUE TITLE
Please test out the new version of Islandora Advanced Search

### ISSUE THREAD

**Issue by kylehuynh205** [Islandora/documentation#2001]
**The original ticket:** https://github.com/Islandora/documentation/issues/1851
Related issue: https://github.com/Islandora/documentation/issues/2000

## Purpose / why

This module [Advanced Search](https://github.com/digitalutsc/advanced_search/tree/contrib) provides improvements to the [Islandora Advanced Search](https://github.com/Islandora/islandora/tree/8.x-1.x/modules/islandora_advanced_search) module.

## Installation
- `git clone https://github.com/digitalutsc/advanced_search` to `/var/www/html/drupal/web/contrib/`
- Use `drush en -y advanced_search` to enable the module or enable it at `/admin/module`
- Disable Islandora Advanced Search if it's enabled before. 
- Sample data can be used by ingesting with Islandora workbench, https://docs.google.com/spreadsheets/d/1DV0Ka0ZafZq3RgCn0x_AetFtlmnMuNFltzck2QL0ApY/edit#gid=994664908

## What changes were made?

- This module is abstracted to a Drupal module instead of [a sub-module inside Islandora Core](https://github.com/Islandora/islandora/tree/8.x-1.x/modules/islandora_advanced_search) and work independently from Islandora Core.
- Provides default and general css style for the Advanced Search Results block and List/Grid switcher based on the work completed by born-digital in their recently contributed Islandora-profile. I have tested the css with Olivero, Bartik, and Bootstrap theme.

    + **Screenshot of the block with the submodule version:** 
![image](https://user-images.githubusercontent.com/7862086/145450939-49a093e9-6686-4cb9-a239-7f5298688c36.png)

   + **Screenshot of the block with this module:** 
![image](https://user-images.githubusercontent.com/7862086/145451215-3e3d1e1d-9235-4bc4-b846-d3e0749d5586.png)

- Adds support for [dismax searching](https://solr.apache.org/guide/8_7/the-standard-query-parser.html) as **_optional feature_** that can be turned on and off in configuration. (as screenshots below)
https://github.com/digitalutsc/advanced_search/tree/contrib#configuration
https://github.com/digitalutsc/advanced_search/tree/contrib#lucene-search-new

- Adds support for wildcat searching as [described in this document](https://solr.apache.org/guide/8_7/the-standard-query-parser.html#wildcard-searches)

- This does not implement edismax, [which has known issues](https://www.drupal.org/docs/contributed-modules/search-api-solr/solr-query-parsers). 

## Proposal

- We would like to contribute back the additional features which we developed from our stack to this module. Therefore, if the module is tested and approved, it can be a replacement for the submodule version which is currently in Islandora Core. Also, the module can be moved to the foundation's github.
